name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  diag-resources:
    name: Diagnostics – Resource Processing (debug)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          add-job-summary: 'never'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Yalnızca kaynak birleştirme/işleme (izole teşhis)
      - name: Merge & process resources (debug)
        run: ./gradlew :app:clean :app:mergeDebugResources :app:processDebugResources --stacktrace --info --no-daemon

      # Teşhis görevleri (app/build.gradle içindeki copyMergedResForDiag ve diagSplashAttrs)
      - name: Run diagnostics (debug)
        run: ./gradlew :app:copyMergedResForDiag :app:diagSplashAttrs --stacktrace --info --no-daemon

      - name: Upload diagnostics artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: resource-diagnostics-debug
          path: |
            app/build/diagnostics/**
            app/build/intermediates/merged_res/debug/values/**

  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    needs: diag-resources

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          add-job-summary: 'never'

      # Mevcut akıştaki doğrulama adımı
      - name: Verify Gradle wrapper on runner
        run: |
          ls -l gradle/wrapper || true
          unzip -p gradle/wrapper/gradle-wrapper.jar META-INF/MANIFEST.MF | sed -n '1,20p' || true
          jar tf gradle/wrapper/gradle-wrapper.jar | head -n 10 || true

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew --no-daemon clean assembleDebug --stacktrace --info

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
