name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Inspect Gradle wrapper JAR
        run: |
          set -e
          sudo apt-get update -y && sudo apt-get install -y unzip
          if [ -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "✅ Found gradle/wrapper/gradle-wrapper.jar"
            unzip -l gradle/wrapper/gradle-wrapper.jar | sed -n '1,200p'
          else
            echo "❌ gradle/wrapper/gradle-wrapper.jar NOT FOUND"
            echo "Repo tree for context:" 
            ls -R
            exit 1
          fi

      - name: Build debug APK
        run: ./gradlew --no-daemon clean :app:assembleDebug --stacktrace --warning-mode all
