name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # ÖNEMLİ: Gradle cache ve configuration cache yönetimi için resmi aksiyon.
      # Manuel actions/cache kaldırıldı → 400 Bad Request riski biter.
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # İsteğe bağlı: build scan kapalı; cache ve wrapper doğrulama açık.
          add-job-summary: false

      - name: Verify Gradle wrapper on runner
        run: |
          ls -l gradle/wrapper || true
          unzip -p gradle/wrapper/gradle-wrapper.jar META-INF/MANIFEST.MF | sed -n '1,20p' || true
          jar tf gradle/wrapper/gradle-wrapper.jar | head -n 10 || true

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
