name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0

      # This action adds a specific Gradle version to PATH
      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"

      # Sanity check: confirm gradle is on PATH and show version
      - name: Check Gradle availability
        shell: bash
        run: |
          which gradle || true
          gradle -v || true

      - name: Build debug APK (verbose)
        shell: bash
        run: |
          set -eo pipefail
          mkdir -p build-logs
          # Pre-create the log so artifact upload always finds a file
          : > build-logs/assembleDebug.log
          gradle --no-daemon clean :app:assembleDebug --stacktrace --info --warning-mode all \
            | tee -a build-logs/assembleDebug.log

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build-logs/*.log
          if-no-files-found: warn

      - name: Upload APK (success only)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
