name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Sadece cmdline-tools kur; paketleri ve lisansları biz yöneteceğiz
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: false
          log-accepted-android-sdk-licenses: false
          cmdline-tools-version: 12266719

      # sdkmanager yolunu güvenli şekilde seç (latest varsa onu, yoksa en yeni numaralı klasörü)
      - name: Select sdkmanager
        run: |
          CANDIDATE="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          if [ -x "$CANDIDATE" ]; then
            echo "SDKMANAGER=$CANDIDATE" >> $GITHUB_ENV
          else
            NEWEST="$(ls -d ${ANDROID_SDK_ROOT}/cmdline-tools/* 2>/dev/null | grep -E '/[0-9]+' | sort -V | tail -1)"
            echo "Using cmdline-tools at: $NEWEST"
            echo "SDKMANAGER=${NEWEST}/bin/sdkmanager" >> $GITHUB_ENV
          fi

      # Lisansları non-interactive kabul et
      - name: Accept Android SDK licenses
        run: yes | "$SDKMANAGER" --licenses --sdk_root="${ANDROID_SDK_ROOT}"

      # Gerekli paketleri kur (sadece bunlar yeterli)
      - name: Install required Android packages
        run: |
          "$SDKMANAGER" --sdk_root="${ANDROID_SDK_ROOT}" --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle cache (read-only)
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew --no-daemon clean assembleDebug --stacktrace --info

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
