name: Android CI (diagnostic-hard)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-34 build-tools;34.0.0'

      - name: Set up Gradle 8.7 (no wrapper)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"

      # Derleme (javac hatasını ve tüm ayrıntıları gösterecek)
      - name: Build debug APK (verbose)
        run: |
          ./gradlew --no-daemon --stacktrace --info \
            :app:compileDebugJavaWithJavac \
            :app:assembleDebug

      # Düşerse, hedefli teşhis logları üret
      - name: Build debug APK (verbose → log dosyasına)
        if: failure()
        run: |
          set -eo pipefail
          mkdir -p build-logs
          gradle --no-daemon clean :app:assembleDebug --stacktrace --info --warning-mode all | tee build-logs/assembleDebug.log || true

      - name: Diagnose Java compile (if failed)
        if: failure()
        run: |
          set -eo pipefail
          mkdir -p build-logs
          gradle --no-daemon :app:compileDebugJavaWithJavac --stacktrace --info | tee build-logs/compileDebugJavaWithJavac.log || true

      - name: Diagnose resources (AAPT2) (if failed)
        if: failure()
        run: |
          set -eo pipefail
          mkdir -p build-logs
          gradle --no-daemon :app:processDebugResources --stacktrace --info | tee build-logs/processDebugResources.log || true

      - name: Diagnose manifest merge (if failed)
        if: failure()
        run: |
          set -eo pipefail
          mkdir -p build-logs
          gradle --no-daemon :app:processDebugMainManifest --stacktrace --info | tee build-logs/processDebugMainManifest.log || true

      - name: Upload logs (ALWAYS)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build-logs/*.log
          if-no-files-found: warn

      - name: Upload APK (success only)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
