name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Android SDK'yi kurar (sdkmanager/cmdline-tools dahil)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Gradle'ı wrapper KULLANMADAN kuruyoruz (bozuk wrapper'a hiç dokunmuyoruz)
      - name: Set up Gradle 8.7 (no wrapper)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"

      # Gerekli platform ve build-tools'ları al (gerekirse sürümü değiştir)
      - name: Install Android SDK components
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"

      # DİKKAT: ./gradlew YOK! Doğrudan 'gradle' komutu kullanılıyor
      - name: Build debug APK
        run: |
          gradle --no-daemon clean :app:assembleDebug --stacktrace --warning-mode all

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
