name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Gradle'ı WRAPPER KULLANMADAN 8.7 olarak kur
      - name: Set up Gradle 8.7 (no wrapper)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'
          cache-read-only: false

      - name: Build debug APK
        run: |
          gradle --no-daemon clean :app:assembleDebug --stacktrace --warning-mode all

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
