name: Android CI (diagnostic-hard)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: "platforms;android-34 build-tools;34.0.0"

      - name: Set up Gradle 8.7 (no wrapper)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"

      # Ana derleme - ayrıntılı log
      - name: Build debug APK (verbose → assembleDebug.log)
        run: |
          set -eo pipefail
          mkdir -p build-logs
          gradle --no-daemon clean :app:assembleDebug --stacktrace --info --warning-mode all \
            | tee build-logs/assembleDebug.log

      # Düşerse: Java derlemesini ayrı logla dene
      - name: Diagnose compileDebugJavaWithJavac (if failed)
        if: failure()
        run: |
          set -eo pipefail
          mkdir -p build-logs
          gradle --no-daemon :app:compileDebugJavaWithJavac --stacktrace --info \
            | tee build-logs/compileDebugJavaWithJavac.log || true

      # Düşerse: Kaynak işleme (AAPT2)
      - name: Diagnose processDebugResources (if failed)
        if: failure()
        run: |
          set -eo pipefail
          mkdir -p build-logs
          gradle --no-daemon :app:processDebugResources --stacktrace --info \
            | tee build-logs/processDebugResources.log || true

      # Düşerse: Manifest birleştirme
      - name: Diagnose processDebugMainManifest (if failed)
        if: failure()
        run: |
          set -eo pipefail
          mkdir -p build-logs
          gradle --no-daemon :app:processDebugMainManifest --stacktrace --info \
            | tee build-logs/processDebugMainManifest.log || true

      # ⬇️ Düşerse: Paketleme adımı (tam istediğin adım)
      - name: Diagnose packageDebug (if failed)
        if: failure()
        run: |
          set -eo pipefail
          mkdir -p build-logs
          gradle --no-daemon :app:packageDebug --stacktrace --info \
            | tee build-logs/packageDebug.log || true

      # Logları her durumda yükle
      - name: Upload logs (ALWAYS)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build-logs/*.log
          if-no-files-found: warn

      # Başarılıysa APK’yı yükle
      - name: Upload APK (success only)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
```0
