name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Android SDK + cmdline-tools kurulumu
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          cmdline-tools-version: 12266719

      # İndirilen en yeni cmdline-tools klasörünü bul ve SDKMANAGER env olarak ayarla
      - name: Select newest sdkmanager
        run: |
          NEWEST_CTOOLS="$(ls -d ${ANDROID_SDK_ROOT}/cmdline-tools/* 2>/dev/null \
            | grep -E '/[0-9]+\.[0-9]+$' | sort -V | tail -1)"
          echo "Using cmdline-tools at: ${NEWEST_CTOOLS}"
          echo "SDKMANAGER=${NEWEST_CTOOLS}/bin/sdkmanager" >> $GITHUB_ENV

      # Lisansları non-interactive kabul et (DOĞRU PATH ile)
      - name: Accept Android SDK licenses
        run: yes | "$SDKMANAGER" --licenses --sdk_root="${ANDROID_SDK_ROOT}"

      # Gerekli paketleri indir (DOĞRU PATH ile)
      - name: Install required Android packages
        run: |
          "$SDKMANAGER" --sdk_root="${ANDROID_SDK_ROOT}" --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"
          "$SDKMANAGER" --sdk_root="${ANDROID_SDK_ROOT}" --update

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew --no-daemon clean assembleDebug --stacktrace --info

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
