name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up JDK 17 (Gradle 8.x / AGP 8.x için Java 17 gereklidir)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK (platform 34 ve build-tools 34.0.0 yükleniyor)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: 'yes'
          packages: |
            platforms;android-34
            build-tools;34.0.0

      # Ensure Gradle wrapper is executable
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Build the debug APK
      - name: Build debug APK
        run: ./gradlew --no-daemon clean assembleDebug

      # Upload the debug APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
