name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Android SDK (cmdline-tools) + lisans
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          cmdline-tools-version: 12266719

      - name: Accept Android SDK licenses (non-interactive)
        run: |
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --licenses --sdk_root="${ANDROID_SDK_ROOT}"

      # Gerekli paketler (compileSdk/targetSdk 34 için)
      - name: Install required Android packages
        run: |
          "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${ANDROID_SDK_ROOT}" \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"

      # (Teşhis) Menü dosyalarını ve res/menu ağacını göster
      - name: List menu XML files (diagnostic)
        run: |
          echo "Listing files matching menu*.xml under res:"
          find app/src/main/res -type f -name "menu*.xml" -print || true
          echo "Res/menu tree (if exists):"
          (ls -la app/src/main/res/menu || true)

      # (Opsiyonel bir kerelik) Gradle cache temizliği
      - name: Clear Gradle caches (one-off)
        run: rm -rf $HOME/.gradle/caches

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Gradle cache (temiz başlat + cleanup)
      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          gradle-home-cache-cleanup: true

      # Derleme (detaylı log)
      - name: Build debug APK
        run: ./gradlew --no-daemon clean assembleDebug --stacktrace --info --warning-mode all

      # Artefakt yükleme
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
