name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true         # <-- BURASI
          cmdline-tools-version: 12266719
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
